lang: en

# Delay after which the warning message is sent to the player (seconds) | Lang entry: "notification.afk_warning"
# e.g., if set to 60, the player will receive a warning message after 1 minute of inactivity
warning-delay: 60

# Delay after which a player is marked as AFK (seconds)
afk-delay: 600

# Delay after which a player marked as AFK is connected to the AFK server (seconds)
action-delay: 30

# Action to be performed after action delay is reached. Possible values: "kick", "connect", "nothing".
# "kick" - player is kicked from the server
# "connect" - player is connected to the server specified in the "afk-server-name" option
# "nothing" - nothing happens
action: "kick"

# Server name to which the player is connected when the action is set to "connect"
# afk-server-name: "afk"