lang: en

# Delay after which the warning message is sent to the player (seconds) | Lang entry: "notification.afk_warning"
# e.g., if set to 300, the player will receive a warning message after 5 minutes of inactivity
warning-delay: 300

# Delay after which a player is marked as AFK (seconds)
# e.g., if set to 600, the player will be marked as AFK after 10 minutes of inactivity
afk-delay: 600

# Delay after which a player marked as AFK is connected to the AFK server (seconds)
# e.g., if set to 630, the player will be connected to the AFK server or kicked after 10 minutes and 30 seconds of inactivity
action-delay: 630

# Action to be performed after action delay is reached. Possible values: "kick", "connect", "nothing".
# "kick" - player is kicked from the server
# "connect" - player is connected to the server specified in the "afk-server-name" option
# "nothing" - nothing happens
action: "kick"

# Server name to which the player is connected when the action is set to "connect"
# !!! Only available for BungeeCord and Velocity !!!
afk-server-name: "afk"

# Whether to allow bypass of AFK detection for players with the "afk.bypass" permission
allow-bypass: true